"""empty message

Revision ID: 3dc1213b9539
Revises: 3caaba2a292b
Create Date: 2015-03-24 01:17:25.210765

"""

# revision identifiers, used by Alembic.
revision = '3dc1213b9539'
down_revision = '3caaba2a292b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('local_url', sa.String(length=80), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'local_url')
    ### end Alembic commands ###
