"""empty message

Revision ID: 3ea11540d8d0
Revises: 3f0d61165d93
Create Date: 2015-04-04 01:11:15.038959

"""

# revision identifiers, used by Alembic.
revision = '3ea11540d8d0'
down_revision = '3f0d61165d93'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=20), nullable=True),
    sa.Column('value', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_setting_key'), 'setting', ['key'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_setting_key'), table_name='setting')
    op.drop_table('setting')
    ### end Alembic commands ###
