"""empty message

Revision ID: 3f0d61165d93
Revises: 2022297e5114
Create Date: 2015-03-29 03:41:44.807692

"""

# revision identifiers, used by Alembic.
revision = '3f0d61165d93'
down_revision = '2022297e5114'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('source_name', sa.String(length=80), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'source_name')
    ### end Alembic commands ###
