"""empty message

Revision ID: 50dd04b8cb0
Revises: 4fffdf3232a
Create Date: 2015-04-07 02:05:02.740193

"""

# revision identifiers, used by Alembic.
revision = '50dd04b8cb0'
down_revision = '4fffdf3232a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('name', sa.String(length=80), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album', 'name')
    ### end Alembic commands ###
